const ALERT='ALERT'
const REFETCH_CHATS='REFETCH_CHATS'
const NEW_ATTACHMENT='NEW_ATTACHMENT'
const NEW_REQUEST='NEW_REQUEST'
const NEW_MESSAGE_ALERT='NEW_MESSAGE_ALERT' // for 2 new message, 3 new message
const NEW_MESSAGE='NEW_MESSAGE' 
const START_TYPING='TYPING'
const STOP_TYPING='STOP_TYPING'
const ONLINE_USERS="ONLINE_USERS"
const CHAT_JOINED="CHAT_JOINED"
const CHAT_LEAVED="CHAT_LEAVED"
export { ALERT, REFETCH_CHATS,NEW_ATTACHMENT,NEW_MESSAGE_ALERT,NEW_REQUEST,NEW_MESSAGE,START_TYPING,STOP_TYPING,CHAT_JOINED,CHAT_LEAVED,ONLINE_USERS }