const ALERT='ALERT'
const REFETCH_CHATS='REFETCH_CHATS'
const NEW_ATTACHMENT='NEW_ATTACHMENT'
const NEW_REQUEST='NEW_REQUEST'
const NEW_MESSAGE_ALERT='NEW_MESSAGE_ALERT' // for 2 new message, 3 new message
const NEW_MESSAGE='NEW_MESSAGE' // f
export { ALERT, REFETCH_CHATS,NEW_ATTACHMENT,NEW_MESSAGE_ALERT,NEW_REQUEST,NEW_MESSAGE }